### ISSUE TITLE
Todos of brewfile.sh

### ISSUE THREAD

**Issue by kwappa** [kwappa/dotfiles#1]
# Todos
- [x] write script to install Ricty
  - [ ] remove unneccessary libs after instllation
- [x] install homebrew-cask
